AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiEndpoint:
    Type: String
  
  TamsConnectionArn:
    Type: String

  ApiStackName:
    Type: String

Resources:
  LoopRecorder:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/loopRecorder.yaml
      DefinitionSubstitutions:
        ConnectionArn: !Ref TamsConnectionArn
        TamsEndpoint: !Ref ApiEndpoint
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource:
                - !Ref TamsConnectionArn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub
                  - arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/${TamsConnection}/*
                  - TamsConnection: !Select [1, !Split [/, !Ref TamsConnectionArn]]
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - GET
                StringLike:
                  states:HTTPEndpoint:
                    - !Sub ${ApiEndpoint}/flows/*
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - DELETE
                StringLike:
                  states:HTTPEndpoint:
                    - !Sub ${ApiEndpoint}/flows/*
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            Name: !Ref ApiStackName
            ScheduleExpression: rate(1 minute)
