/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowCoreSegmentDuration } from "./flow-core-segment-duration";
import { ContainerMapping1 } from "./container-mapping1";
import { AudioFlow } from "./audio-flow";
import { VideoFlow } from "./video-flow";
import { CollectionItem } from "./collection-item";
import { DataFlowEssenceParameters } from "./data-flow-essence-parameters";
import { MultiEssenceFlow } from "./multi-essence-flow";
import { DataFlow } from "./data-flow";
import { ImageFlow } from "./image-flow";

/**
 * Describes a Flow
 */
/**
 * @type Flow
 * Describes a Flow
 * @export
 */
export type Flow =
  | AudioFlow
  | DataFlow
  | MultiEssenceFlow
  | VideoFlow
  | ImageFlow;
