AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  UserPoolId:
    Type: String

  ApiEndpoint:
    Type: String

  UserPoolClientId:
    Type: String

  TokenUrl:
    Type: String

  AuthRoleName:
    Type: String

  OpenIdAuthLayerArn:
    Type: String

  TamsConnectionArn:
    Type: String

  SegmentIngestQueueUrl:
    Type: String

  SegmentIngestQueueArn:
    Type: String

  ParentStackName:
    Type: String

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 30
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.13
    Architectures:
      - arm64

Resources:
  AuthRolePolicyReplication:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref AuthRoleName
      PolicyName: !Ref AWS::StackName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ConnectionsParameter}
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource:
              - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ReplicationBatch.Name}
              - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ReplicationCreateRule.Name}
              - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ReplicationDeleteRule.Name}

  Api:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Prod
      Auth:
        ApiKeyRequired: True
        UsagePlan:
          CreateUsagePlan: PER_API

  WebhookReceiverFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: VPC not required
          - id: W92
            reason: ReservedConcurrentExecutions not required
    Properties:
      CodeUri: functions/webhook-receiver/
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:7
      Environment:
        Variables:
          QUEUE_URL: !Ref SegmentIngestQueueUrl
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !Ref SegmentIngestQueueArn
      Events:
        postEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{id}
            Method: post

  FlowHierachyResolverFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Resource level permissions not possible
          - id: W89
            reason: VPC not required
          - id: W92
            reason: ReservedConcurrentExecutions not required
    Properties:
      CodeUri: functions/flow-hierarchy-resolver/
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:7
        - !Ref OpenIdAuthLayerArn
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: tams-tools
          POWERTOOLS_METRICS_NAMESPACE: TAMS-Tools
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:DescribeConnection
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:connection/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*/*

  ConnectionsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AWS::StackName}-connections
      Type: String
      DataType: text
      Description: TAMS Replication connections
      Value: "{}"

  ReplicationFlowLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: Encryption no required.
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${ParentStackName}-replication-flow
      RetentionInDays: 30

  ReplicationFlow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Tracing:
        Enabled: True
      Logging:
        Level: ALL
        IncludeExecutionData: True
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ReplicationFlowLogGroup.Arn
      DefinitionUri: statemachines/replicationflow.yaml
      DefinitionSubstitutions:
        ConnectionArn: !Ref TamsConnectionArn
        TamsEndpoint: !Ref ApiEndpoint
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:PutResourcePolicy
                - logs:DescribeLogGroups
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:DescribeResourcePolicies
                - logs:GetLogDelivery
                - logs:ListLogDeliveries
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ReplicationFlowLogGroup}:log-stream:*
            - Effect: Allow
              Action:
                - logs:PutDestination
                - logs:PutDestinationPolicy
              Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ReplicationFlowLogGroup}:destination:*
            - Effect: Allow
              Action:
                - logs:PutSubscriptionFilter
              Resource:
                - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ReplicationFlowLogGroup}
                - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ReplicationFlowLogGroup}:destination:*
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource:
                - !Ref TamsConnectionArn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub
                  - arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/${TamsConnection}/*
                  - TamsConnection: !Select [1, !Split [/, !Ref TamsConnectionArn]]
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - GET
                    - PUT
                StringLike:
                  states:HTTPEndpoint:
                    - !Sub ${ApiEndpoint}/flows/*

  ReplicationBatch:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/replicationbatch.yaml
      DefinitionSubstitutions:
        FlowHierachyResolverFunctionArn: !GetAtt FlowHierachyResolverFunction.Arn
        ReplicationFlowArn: !Ref ReplicationFlow
        ConnectionArn: !Ref TamsConnectionArn
        TamsEndpoint: !Ref ApiEndpoint
        QueueUrl: !Ref SegmentIngestQueueUrl
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt FlowHierachyResolverFunction.Arn
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ReplicationFlow.Name}
            - Effect: Allow
              Action:
                - states:DescribeExecution
                - states:StopExecution
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:execution:${ReplicationFlow.Name}:*
            - Effect: Allow
              Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:connection/*/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*/*
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - GET
                StringLike:
                  states:HTTPEndpoint:
                    - "*/flows/*/segments"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !Ref SegmentIngestQueueArn

  ReplicationCreateRule:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/replicationcreaterule.yaml
      DefinitionSubstitutions:
        FlowHierachyResolverFunctionArn: !GetAtt FlowHierachyResolverFunction.Arn
        ReplicationFlowArn: !Ref ReplicationFlow
        ConnectionArn: !Ref TamsConnectionArn
        TamsEndpoint: !Ref ApiEndpoint
        ApiEndpoint: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Api.Stage}
        ApiKey: !Ref ApiApiKey
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt FlowHierachyResolverFunction.Arn
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ReplicationFlow.Name}
            - Effect: Allow
              Action:
                - states:DescribeExecution
                - states:StopExecution
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:execution:${ReplicationFlow.Name}:*
            - Effect: Allow
              Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:connection/*/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*/*
            - Effect: Allow
              Action:
                - apigateway:GET
              Resource:
                - !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}::/apikeys/${ApiApiKey}
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - POST
                StringLike:
                  states:HTTPEndpoint:
                    - "*/service/webhooks"

  ReplicationDeleteRule:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/replicationdeleterule.yaml
      DefinitionSubstitutions:
        FlowHierachyResolverFunctionArn: !GetAtt FlowHierachyResolverFunction.Arn
        ReplicationFlowArn: !Ref ReplicationFlow
        ConnectionArn: !Ref TamsConnectionArn
        TamsEndpoint: !Ref ApiEndpoint
        ApiEndpoint: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Api.Stage}
        ApiKey: !Ref ApiApiKey
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource:
                - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:connection/*/*
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*/*
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource:
                - !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*
              Condition:
                StringEquals:
                  states:HTTPMethod:
                    - POST
                StringLike:
                  states:HTTPEndpoint:
                    - "*/service/webhooks"

Outputs:
  ParameterName:
    Value: !Ref ConnectionsParameter

  ReplicationBatchArn:
    Value: !Ref ReplicationBatch

  ReplicationCreateRuleArn:
    Value: !Ref ReplicationCreateRule

  ReplicationDeleteRuleArn:
    Value: !Ref ReplicationDeleteRule
